language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t namnh06/docker-react-101 -f Dockerfile.dev .

script:
    - docker run -e CI=true namnh06/docker-react-101 npm test

deploy:
    provider: elasticbeanstalk
    region: "ap-southeast-2"
    app: "docker"
    env: "Docker-env-1"
    bucket_name: "elasticbeanstalk-ap-southeast-2-390526702605"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY