sudo: required
services:
    - docker

before_install:
    - docker build -t namnh06/docker-react-101 -f Dockerfile.dev .

script:
    - docker run namnh06/docker-react-101 npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "ap-southeast-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-ap-southeast-2-390526702605"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"